# Generated by Django 4.1.1 on 2023-02-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_anio_cliente_contratacion_informacion_mes_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratacion',
            name='estado',
            field=models.CharField(default='d', max_length=1),
        ),
    ]
