# Generated by Django 4.1.1 on 2023-02-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contratacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratacion',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
