# Generated by Django 4.2.1 on 2023-05-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contratacion_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacion',
            name='logo',
            field=models.ImageField(default='descarga.png', upload_to='logo'),
        ),
        migrations.DeleteModel(
            name='Cuenta',
        ),
    ]
