# Generated by Django 4.2.1 on 2023-06-19 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_informacion_logo_delete_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratacion',
            name='estado',
            field=models.CharField(choices=[('D', 'Al día'), ('P', 'Pendiente'), ('C', 'Cancelado')], default='D', max_length=1),
        ),
        migrations.CreateModel(
            name='ReporteFallo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=256)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('S', 'Solucionado')], default='P', max_length=1)),
                ('contratacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.contratacion')),
                ('tecnico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_asignados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
