# Generated by Django 4.2.1 on 2023-06-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contratacion_ultimo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratacion',
            name='ultimo_pago',
            field=models.DateField(auto_now_add=True),
        ),
    ]
