# Generated by Django 4.2.1 on 2023-07-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_contratacion_ultimo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratacion',
            name='direccion',
        ),
        migrations.AlterField(
            model_name='reportefallo',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('E', 'En progreso'), ('S', 'Solucionado')], default='P', max_length=1),
        ),
    ]
