# Generated by Django 4.2.3 on 2023-07-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_contratacion_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratacion',
            name='direccion',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
